Added Dockerfile for native builds

diff --git a/5.0/Dockerfile b/5.0/Dockerfile
--- a/5.0/Dockerfile
+++ b/5.0/Dockerfile
@@ -1,35 +1,43 @@
-FROM debian:stretch-slim
+# BUILD redisfab/redis-${ARCH}-${OSNICK}:5.0.5
 
-# add our user and group first to make sure their IDs get assigned consistently, regardless of whatever dependencies get added
-RUN groupadd -r redis && useradd -r -g redis redis
+# OS=debian:buster-slim|debian:stretch-slim|ubuntu:bionic
+ARG OS=debian:buster-slim
+
+# OSNICK=stretch|bionic|buster
+ARG OSNICK=buster
+
+# ARCH=x64|arm64v8|arm32v7
+ARG ARCH=x64
+
+#----------------------------------------------------------------------------------------------
+FROM ${OS} as builder
+
+ENV X_NPROC "cat /proc/cpuinfo|grep processor|wc -l"
+
+ENV REDIS_DEPENDS "ca-certificates dirmngr gnupg wget gcc libc6-dev make"
+RUN set -ex; \
+	apt-get -qq update; \
+	apt-get -qq install -y --no-install-recommends $REDIS_DEPENDS
 
 # grab gosu for easy step-down from root
 # https://github.com/tianon/gosu/releases
-ENV GOSU_VERSION 1.10
+ENV GOSU_VERSION 1.11
 RUN set -ex; \
-	\
-	fetchDeps=" \
-		ca-certificates \
-		dirmngr \
-		gnupg \
-		wget \
-	"; \
-	apt-get update; \
-	apt-get install -y --no-install-recommends $fetchDeps; \
-	rm -rf /var/lib/apt/lists/*; \
-	\
 	dpkgArch="$(dpkg --print-architecture | awk -F- '{ print $NF }')"; \
-	wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch"; \
-	wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch.asc"; \
+	wget -q -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch"; \
+	wget -q -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch.asc"
+
+# note: gpg sometimes fails due to network problems, disabling ipv6 helps
+
+RUN set -ex; \
 	export GNUPGHOME="$(mktemp -d)"; \
+	echo "disable-ipv6" >> $GNUPGHOME/dirmngr.conf; \
 	gpg --batch --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4; \
 	gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu; \
 	gpgconf --kill all; \
 	rm -r "$GNUPGHOME" /usr/local/bin/gosu.asc; \
-	chmod +x /usr/local/bin/gosu; \
-	gosu nobody true; \
-	\
-	apt-get purge -y --auto-remove $fetchDeps
+	chmod 755 /usr/local/bin/gosu; \
+	gosu nobody true
 
 ENV REDIS_VERSION 5.0.5
 ENV REDIS_DOWNLOAD_URL http://download.redis.io/releases/redis-5.0.5.tar.gz
@@ -37,48 +45,48 @@ ENV REDIS_DOWNLOAD_SHA 2139009799d21d8ff94fc40b7f36ac46699b9e1254086299f8d3b223c
 
 # for redis-sentinel see: http://redis.io/topics/sentinel
 RUN set -ex; \
-	\
-	buildDeps=' \
-		ca-certificates \
-		wget \
-		\
-		gcc \
-		libc6-dev \
-		make \
-	'; \
-	apt-get update; \
-	apt-get install -y $buildDeps --no-install-recommends; \
-	rm -rf /var/lib/apt/lists/*; \
-	\
-	wget -O redis.tar.gz "$REDIS_DOWNLOAD_URL"; \
+	wget -q -O redis.tar.gz "$REDIS_DOWNLOAD_URL"; \
 	echo "$REDIS_DOWNLOAD_SHA *redis.tar.gz" | sha256sum -c -; \
 	mkdir -p /usr/src/redis; \
-	tar -xzf redis.tar.gz -C /usr/src/redis --strip-components=1; \
-	rm redis.tar.gz; \
-	\
-# disable Redis protected mode [1] as it is unnecessary in context of Docker
+	tar -xzf redis.tar.gz -C /usr/src/redis --strip-components=1
+
+# Disable Redis protected mode [1] as it is unnecessary in context of Docker
 # (ports are not automatically exposed when running inside Docker, but rather explicitly by specifying -p / -P)
 # [1]: https://github.com/antirez/redis/commit/edd4d555df57dc84265fdfb4ef59a4678832f6da
+
+RUN set -ex; \
 	grep -q '^#define CONFIG_DEFAULT_PROTECTED_MODE 1$' /usr/src/redis/src/server.h; \
 	sed -ri 's!^(#define CONFIG_DEFAULT_PROTECTED_MODE) 1$!\1 0!' /usr/src/redis/src/server.h; \
-	grep -q '^#define CONFIG_DEFAULT_PROTECTED_MODE 0$' /usr/src/redis/src/server.h; \
-# for future reference, we modify this directly in the source instead of just supplying a default configuration flag because apparently "if you specify any argument to redis-server, [it assumes] you are going to specify everything"
-# see also https://github.com/docker-library/redis/issues/4#issuecomment-50780840
+	grep -q '^#define CONFIG_DEFAULT_PROTECTED_MODE 0$' /usr/src/redis/src/server.h
+
+# For future reference, we modify this directly in the source instead of just supplying a default
+# configuration flag because apparently "if you specify any argument to redis-server, 
+# [it assumes] you are going to specify everything".
+# See also https://github.com/docker-library/redis/issues/4#issuecomment-50780840
 # (more exactly, this makes sure the default behavior of "save on SIGTERM" stays functional by default)
-	\
-	make -C /usr/src/redis -j "$(nproc)"; \
-	make -C /usr/src/redis install; \
-	\
-	rm -r /usr/src/redis; \
-	\
-	apt-get purge -y --auto-remove $buildDeps
+
+# note: ARCH may break build if non-empty
+
+RUN set -ex; \
+	ARCH= make -C /usr/src/redis -j $(eval "$X_NPROC"); \
+	make -C /usr/src/redis install
+
+#----------------------------------------------------------------------------------------------
+FROM ${OS}
+
+# Add our user and group first to make sure their IDs get assigned consistently, 
+# regardless of whatever dependencies get added
+RUN groupadd -r redis && useradd -r -g redis redis
+
+COPY --from=builder /usr/local/ /usr/local/
 
 RUN mkdir /data && chown redis:redis /data
 VOLUME /data
 WORKDIR /data
 
 COPY docker-entrypoint.sh /usr/local/bin/
-ENTRYPOINT ["docker-entrypoint.sh"]
+RUN chmod 755 /usr/local/bin/docker-entrypoint.sh
 
+ENTRYPOINT ["docker-entrypoint.sh"]
 EXPOSE 6379
 CMD ["redis-server"]
